### ISSUE TITLE
Colliding entity with block java.lang.NoSuchMethodError: com.gmail.rohzek.blocks.CheshireRose.spawnHearts

### ISSUE THREAD

**Issue by sandalle** [Rohzek/SimpleOreGeneration#9]
I noticed this after updating Simple Ore Generation to 3.4.3, but still have the problem after downgrading to 3.4.2 (I hadn't restarted the server in a few days).

Crash Report (using 3.4.2, but also happens with 3.4.3): 
[crash-2017-05-20_21.11.27-server.txt](https://github.com/Rohzek/SimpleOreGeneration/files/1016628/crash-2017-05-20_21.11.27-server.txt)

To fix it, I had to revert my world to a backup (I had just taken one, luckily ;)) and disable the Cheshire Rose in the simpleoregen/options.cfg, then start with the restored world (using SimpleOreGen 3.4.3).
`B:gfFlowerDisable=true`

**Comment by Rohzek** [comment]
Sorry for the trouble. It should be fixed for sure this time, in 3.4.4 (Although if the backup was before they were generated, having them disabled in the config is just as good, since there wont be any in the world haha.)
I'll leave this open until it can be confirmed for sure.

**Comment by sandalle** [comment]
I restored my broken world and tested with 3.4.4, works fine with Cheshire Rose enabled, thanks for the quick fix! :) Also thanks for the mod, it really helps consolidate ore generation.
